baseURL = 'https://home.ljga.net'
languageCode = 'en-gb'
title = 'Start here'
theme = 'startpage'
publishdir = './docs/'

# [[params.searchEngines]]
#   name = "Stack Overflow"
#   activated = true
#   url = "https://stackoverflow.com/search"
#   searchkey = "q"
